### PR TITLE
pre-1.13 support

### PR DESCRIPTION
**Pull request by SecurityInsanity**
this commit adds in a module for 1.13 NMS. I haven't been able to look into the loading error mentioned in #180 , due to not getting a successful build of the actual: `Plugin` maven module.

At first I got:

```
[ERROR] Failed to execute goal on project orebfuscator: Could not resolve dependencies for project com.lishid:orebfuscator:jar:4.4.0-SNAPSHOT: Failed to collect dependencies at com.comphenix.protocol:ProtocolLib-API:jar:4.0.0: Failed to read artifact descriptor for com.comphenix.protocol:ProtocolLib-API:jar:4.0.0: Could not transfer artifact com.comphenix.protocol:ProtocolLib-API:pom:4.0.0 from/to techcable-repo (https://repo.techcable.net/content/groups/public/): Failed to transfer file: https://repo.techcable.net/content/groups/public/com/comphenix/protocol/ProtocolLib-API/4.0.0/ProtocolLib-API-4.0.0.pom. Return code is: 502 , ReasonPhrase:Bad Gateway. -> [Help 1]
```

Changing ProtocolLib to a newer version locally like: 4.2.1 that exists for sure results in:

```
[ERROR] Failed to execute goal on project orebfuscator: Could not resolve dependencies for project com.lishid:orebfuscator:jar:4.4.0-SNAPSHOT: Failed to collect dependencies at com.lishid:orebfuscator-api:jar:API: Failed to read artifact descriptor for com.lishid:orebfuscator-api:jar:API: Could not transfer artifact com.lishid:orebfuscator-api:pom:API from/to techcable-repo (https://repo.techcable.net/content/groups/public/): Failed to transfer file: https://repo.techcable.net/content/groups/public/com/lishid/orebfuscator-api/API/orebfuscator-api-API.pom. Return code is: 502 , ReasonPhrase:Bad Gateway. -> [Help 1]
```

Even after a: `mvn install` in the API directory.

I'm happy to look into these build errors if you think it's not something wrong with just my personal environment. That being said the NMS code for 1.13 can be built with: `mvn package`.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Thanks! 

Does this work? I had started down a similar path and I was not convinced it would actually work due to, basically, trying to shoe-horn the new "anti-byte-data" approach of 1.13 into the very, very old-school approach of pre-1.13 orebfuscator.

I'll post my efforts hopefully tomorrow and link here for you to look at, basically I drop all pre-1.13 support and have begun to rewrite all impacted code to directly support 1.13+ without reliance on downconvert and such.

Naturally, this makes the workload larger....


Let me know. Thanks so much!

**Comment by SecurityInsanity** [comment]
I haven't actually been able to verify to that (due to not being able to build), though I figured it was worth a shot.

I was actually posting this here to hope that you had some insight to the build errors, and something could be up heh.

As for supporting just 1.13 that's fine for our use case, I'd be happy to review the code!

**Comment by ProgrammerDan** [comment]
Yeah, that build error is weird. I get some weird errors and have to mess with the poms to build in Eclipse, while it would build fine on prompt for me... (Eclipse doesn't support target redirection in pom.xml -- maven generally has no issue).

The bigger issues came up when I updated the Plugin to 1.13 instead of 1.12 ... then everything went red :D . 

I'll try to post what I have soon, we did some similar things in the 1.13 R1 NMS bits.

I'm mucking in the ChunkMapManager now... it's a mess ... everything is fine-tuned for 255 block palette size and with that out the window I'm trying to figure out what went on originally and expand the palette map allowances...

**Comment by SecurityInsanity** [comment]
Yeah that's the change I was most worried about having to rewrite stuff. I haven't dug too deep into the ChunkMapManager, but I'll take a look at getting it to build locally for me so I can delve in aswell.

**Comment by ProgrammerDan** [comment]
Sounds great :) Thanks for diving in!

**Comment by SecurityInsanity** [comment]
Turns out all I had to do was bump ProtocolLib to 4.2.1, and remove support for anything less <1.13 to get it to build. Not sure exactly what the transitive problem was with the build system, but hey as long as it builds now.

**Comment by SecurityInsanity** [comment]
Sounds good :+1: I'll go ahead and close this PR and wait for that one to go up.

**Pull request closed without merging**
