### PR TITLE
v1_14_R1 version

### PR DESCRIPTION
**Pull request by JayJay1989**
Changelog:
- Removed broken repo for building it in IntelliJ
- Adding 'v1_14_R1' to the main class
- Adding new 1.14 blocks that needs to be hidden.

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Thank you! Will review and merge if all good tonight

**Comment by JonMagon** [comment]
@JayJay1989 on 1.14.2 Spigot doesn't work, I've compiled files from your repo. It's just spaming in console

> [11:59:04] [Server thread/ERROR]: ChunkX = -59, chunkZ = -69
[11:59:04] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[11:59:04] [Server thread/ERROR]: ChunkX = -59, chunkZ = -85
[11:59:04] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[11:59:04] [Server thread/ERROR]: ChunkX = -59, chunkZ = -68
[11:59:04] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[11:59:04] [Server thread/ERROR]: ChunkX = -59, chunkZ = -72
[11:59:04] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[11:59:04] [Server thread/ERROR]: ChunkX = -59, chunkZ = -73
[11:59:04] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[11:59:04] [Server thread/ERROR]: ChunkX = -59, chunkZ = -74
[11:59:04] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[11:59:05] [Server thread/ERROR]: ChunkX = -59, chunkZ = -81
[11:59:05] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[11:59:05] [Server thread/ERROR]: ChunkX = -59, chunkZ = -80
[11:59:05] [Server thread/WARN]: java.io.IOException: No data to read. byteIndex = 13424
[11:59:05] [Server thread/WARN]:        at com.lishid.orebfuscator.chunkmap.ChunkReader.readLong(ChunkReader.java:62)
[11:59:05] [Server thread/WARN]:        at com.lishid.orebfuscator.chunkmap.ChunkReader.readBlockBits(ChunkReader.java:40)
[11:59:05] [Server thread/WARN]:        at com.lishid.orebfuscator.chunkmap.ChunkMapManager.readLayer(ChunkMapManager.java:348)
[11:59:05] [Server thread/WARN]:        at com.lishid.orebfuscator.chunkmap.ChunkMapManager.moveToNextLayer(ChunkMapManager.java:288)
[11:59:05] [Server thread/WARN]:        at com.lishid.orebfuscator.chunkmap.ChunkMapManager.readNextBlock(ChunkMapManager.java:246)
[11:59:05] [Server thread/WARN]:        at com.lishid.orebfuscator.obfuscation.Calculations.obfuscate(Calculations.java:170)
[11:59:05] [Server thread/WARN]:        at com.lishid.orebfuscator.obfuscation.Calculations.obfuscateOrUseCache(Calculations.java:69)
[11:59:05] [Server thread/WARN]:        at com.lishid.orebfuscator.hook.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:87)
[11:59:05] [Server thread/WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[11:59:05] [Server thread/WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[11:59:05] [Server thread/WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[11:59:05] [Server thread/WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[11:59:05] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[11:59:05] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[11:59:05] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[11:59:05] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[11:59:05] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[11:59:05] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[11:59:05] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[11:59:05] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:193)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:157)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1423)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1396)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:1619)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerChunkMap.a(PlayerChunkMap.java:1019)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$42(PlayerChunkMap.java:611)
[11:59:05] [Server thread/WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[11:59:05] [Server thread/WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[11:59:05] [Server thread/WARN]:        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
[11:59:05] [Server thread/WARN]:        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[11:59:05] [Server thread/WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[11:59:05] [Server thread/WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[11:59:05] [Server thread/WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[11:59:05] [Server thread/WARN]:        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[11:59:05] [Server thread/WARN]:        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$41(PlayerChunkMap.java:610)
[11:59:05] [Server thread/WARN]:        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
[11:59:05] [Server thread/WARN]:        at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[11:59:05] [Server thread/WARN]:        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$39(PlayerChunkMap.java:606)
[11:59:05] [Server thread/WARN]:        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
[11:59:05] [Server thread/WARN]:        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
[11:59:05] [Server thread/WARN]:        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.b(SourceFile:57)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.ThreadedMailbox.e(SourceFile:83)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.ThreadedMailbox.a(SourceFile:123)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.ThreadedMailbox.run(SourceFile:91)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:509)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:200)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:904)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872)
[11:59:05] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805)
[11:59:05] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by JayJay1989** [comment]
Jep,Busy with fixing those errors. I let you know if i got further.

**Comment by JonMagon** [comment]
@JayJay1989 thanks. I've tried with 1.14 and got the same problem.

**Comment by JayJay1989** [comment]
hmm, cant get arround 'ArrayIndexOutOfBoundsException'.

**Comment by JonMagon** [comment]
There's no ArrayIndexOutOfBoundsException with creating new clear server, but it also doesn't work on 1.14. Just start without any errors. I've tried your https://github.com/JayJay1989/Orebfuscator/files/3316604/orebfuscator-4.4.3-SNAPSHOT.jar.zip and compiled by myself from your repo. I'm using Spigot was builded via official BuildTools.jar I can give you access to my test server if you want. How can I contact with you?

**Comment by JayJay1989** [comment]
@JonMagon did you build after my latest commit couple hours ago?

edit: creating new world gives me: 'ArrayIndexOutOfBoundsException' and ' No data to read. byteIndex'
[Latest build](https://github.com/lishid/Orebfuscator/files/3317825/orebfuscator-4.4.4.jar.zip)

**Comment by JonMagon** [comment]
Unfortunately nothing has changed. 
UPD: It says again ArrayIndexOutOfBoundsException with new world

> [15:50:02] [Server thread/INFO]: TPS from last 1m, 5m, 15m: 19.74, 19.94, *20.0
[15:50:02] [Server thread/ERROR]: ChunkX = -3, chunkZ = -29
[15:50:02] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:50:02] [Server thread/ERROR]: ChunkX = -3, chunkZ = -28
[15:50:02] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:50:02] [Server thread/ERROR]: ChunkX = -3, chunkZ = -27
[15:50:02] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:50:02] [Server thread/ERROR]: ChunkX = -3, chunkZ = -26
[15:50:02] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:50:02] [Server thread/ERROR]: ChunkX = -3, chunkZ = -25
[15:50:02] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:50:02] [Server thread/ERROR]: ChunkX = 16, chunkZ = -9
[15:50:02] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:50:02] [Server thread/ERROR]: ChunkX = 17, chunkZ = -9
[15:50:02] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:50:03] [Server thread/ERROR]: ChunkX = -3, chunkZ = -22
[15:50:03] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:50:03] [Server thread/ERROR]: ChunkX = -3, chunkZ = -23
[15:50:03] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:50:03] [Server thread/ERROR]: ChunkX = -3, chunkZ = -21
[15:50:03] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:50:03] [Server thread/ERROR]: ChunkX = -3, chunkZ = -20
[15:50:03] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:50:03] [Server thread/ERROR]: ChunkX = -3, chunkZ = -19
[15:50:03] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException

**Comment by ProgrammerDan** [comment]
Fwiw looks like same issue as in 1.13.2, so fixing it in the one will
likely fix in the other. I think I have an idea where the issue is, just
need time to test

**Comment by HolographicWings** [comment]
> Why? It doesn't work

Doesn't work, i have try to apply the last commit named changes and i find theses errors :
[2019-08-11-6.log](https://github.com/lishid/Orebfuscator/files/3489388/2019-08-11-6.log)

[Orebfuscator sources.zip](https://github.com/lishid/Orebfuscator/files/3489391/Orebfuscator.sources.zip)

**Pull request closed without merging**
