### PR TITLE
Support 1.10

### PR DESCRIPTION
**Pull request by Asgarioth**
Hi guys,

The PR adds 1.10 support (without breaking 1.9.x support) along with minor changes to the pom.xml (add compile-plugin configuration).

Although I think that you are working on this as well I thought I should share it. Feel free to deny the PR if it conflicts with your work. :-)

Regards,
~Asgarioth

### CODE REVIEW

**Comment by Jikoo** [comment]
You should probably add a check to return null if minorBuild is not 1 in case of an update to v1_10_R2 to match the way 1.9 is limited.

**Comment by ProgrammerDan** [comment]
@Aleksey-Terzi Thoughts?

**Comment by Asgarioth** [comment]
@Jikoo: lol. 
I added quite similar code that I've been using in another NMS plugin. Splitting the string isn't really necessary at all.

**Comment by Jikoo** [comment]
@Asgarioth Agreed, no real need for the capturing group or matcher at all, just ease. I prefer my way of parsing the version substring to your split due to it being safe for pre-1.4.5 Bukkit where there is 1 fewer segment to the package name, rare and weird case that that may be. Also, you can split("\\.") to eliminate a useless replace.

**Comment by ProgrammerDan** [comment]
Merged, thank you.

**Pull request merged**
